ARG JAVA_VERSION=11

# This Debian image additionally contains function core tools – useful when using custom extensions
FROM mcr.microsoft.com/azure-functions/java:3.0-java$JAVA_VERSION-core-tools 

# Standard stuff needed for Azure setup
RUN apt update && \
    apt upgrade -y && \
    apt install -y gpg curl lsb-release gnupg ca-certificates apt-transport-https

# Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Tools that we like
RUN apt install -y nano fish vim

EXPOSE 7071 5005

CMD ["/bin/bash"]

