# This docker file is used to build a development container with
#
#  - The Azure image, JVM and CLI tools
#  - And a few development tools
#
# The intent is for the prime-router to be mounted into this container,
# allowing the content of this container to be stable
#
ARG JAVA_VERSION=11

# This Debian image additionally contains function core tools – useful when using custom extensions
FROM mcr.microsoft.com/azure-functions/java:4-java$JAVA_VERSION-core-tools

# Disable SSL verification for agencies that re-sign SSL connections
ARG INSECURE_SSL=false
RUN if [ -n "$INSECURE_SSL" ] && [ "$INSECURE_SSL" = "true" ]; then \
        touch /etc/apt/apt.conf.d/99verify-peer.conf && \
        echo >>/etc/apt/apt.conf.d/99verify-peer.conf "Acquire { https::Verify-Peer false }"; \
    fi

# Standard stuff needed for Azure setup
RUN apt-get clean && \
    apt-get --allow-releaseinfo-change --allow-releaseinfo-change-suite update && \
    apt-get upgrade -y && \
    apt-get --yes install gpg curl lsb-release gnupg ca-certificates apt-transport-https

# Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Tools that we like
RUN apt-get --yes install nano fish vim

CMD ["/bin/bash"]
