#!/bin/bash
#
# This script runs the CLI of the project. 
#
# It handles four different configurations in this order of preference
#  1. Where a fat jar (a jar with all dependencies) is present in the working directory
#  2. Where a fat jar is present in a 'target' subdirectory
#  3. Where a slim jar is present in the working directory and a 'azure-functions/prime-data-hub-router/lib' exists
#  4. Where a slim jar is present in a 'target' subdirectory and the lib sub directory is also present
#
# This script should work on both a Mac and the Dev Docker container

set -e
version=0.1-SNAPSHOT
fat_jar=build/libs/prime-router-$version.jar
lib_dir="build/libs"
fat_jar_name=prime-router-$version-jar-with-dependencies.jar
slim_jar_name=prime-router-$version.jar
lib_name=build/azure-functions/prime-data-hub-router/lib

# find the jar
if [ -f $fat_jar ]; then
  jar=$fat_jar
else
  echo "Could not find a prime-data-hub-router*.jar file"
  exit 1
fi

java -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -jar $jar "$@"
