/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "prime-router"

// Make sure the gradle plugin manager is not using JCenter, which was shutdown
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}