/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "prime-router"

// Make sure the gradle plugin manager is not using JCenter, which was shutdown
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            url = uri("https://jitpack.io")
        }
    }
    includeBuild("../tsGenerate/tsGeneratePlugin")
}
// include("tsGenerateLibrary")
// project(":tsGenerateLibrary").projectDir = file("../tsGenerate/tsGenerateLibrary")
// includeBuild("../tsGenerate/tsGeneratePlugin") {
    /*dependencySubstitution {
        substitute(module("gov.cdc.prime:tsGeneratePlugin:0.2-SNAPSHOT")).using(project(":"))
    }
}*/