@startuml
Client -> Okta: Request Access token
Okta --> Client: Access token
Client -> ReportStream: Use access token
ReportStream -> Okta: Check validity of access token
Okta --> ReportStream: Valid access token
ReportStream -> ReportStream: Check authorization to access resource
ReportStream --> Client: 200 response
@enduml