#!/usr/bin/env python3
# generate-jwt.py
#
# Follow the setup steps in
#       https://auth0.com/blog/how-to-handle-jwt-in-python/
# prior to running this.  Once you have followed those steps, then each subsequent time you need to run it, just do:
#       source .env/bin/activate
#
# How to run this:  python3 ./generate-jwt.py
#
# Be sure to change my_client_id, below, to be your client-id string, as given to you by the ReportStream team.
#
import datetime
import jwt
import math
import os
import platform
import sys
import uuid
from cryptography.hazmat.primitives import serialization

windows = platform.system() == "Windows"
exe = ".exe" if windows else ""

#
# REPLACE THESE WITH YOUR CLIENT-ID, KID ID, AND KEYPAIR FILE
#
my_client_id = "healthy-labs"
my_kid = "default"
my_rsa_keypair_file = "./my-rsa-keypair.pem" # REPLACE THIS WITH A PATH TO YOUR KEYFILE. SEE NOTE BELOW
# ON WINDOWS USE '\\' AS YOUR PATH SEPARATOR (A SINGLE '\' BEGINS AN ESCAPE SEQUENCE))
# FOR EXAMPLE: "C:\\Users\\Some User\\Desktop\\my-rsa-keypair.pem" or ".\\my-rsa-keypair.pem"

#
# Step 1
#
print(
f'''
STEP 1:  Prior to submission, send your public key to ReportStream

This program assumes there is an RSA keypair in the file {my_rsa_keypair_file}

This keypair can be generated by running these commands in that directory:
	openssl{exe} genrsa -out {my_rsa_keypair_file} 2048
	openssl{exe} rsa -in {my_rsa_keypair_file} -outform PEM -pubout -out my-rsa-public-key.pem

Then send the public key file to the ReportStream team.

''')

#
# Step 2
#

try:
    private_key = open(my_rsa_keypair_file, 'r').read()
except FileNotFoundError:
    sys.exit("File "+ my_rsa_keypair_file + " not found. Abort STEP 2.")

key = serialization.load_pem_private_key(private_key.encode(), password=None)

now = math.floor(datetime.datetime.timestamp(datetime.datetime.now()))

header_data = { "kid": f"{my_kid}"}

payload_data = {
    "iss": f"{my_client_id}",
    "sub": f"{my_client_id}",
    "aud": "staging.prime.cdc.gov",
    "exp": now + 300,                                # Expire in 5 minutes
    "jti": str(uuid.uuid4())
}

print(f'The payload is {payload_data}\n')

token = jwt.encode(
    payload=payload_data,
    key=key,
    algorithm='RS256',
    headers=header_data
)

print(
f'''
STEP 2:  At the Time of Submission to ReportStream, generate a signed JWT using your private key

{token}

''')

#
# Examples of Steps 3 and 4
# 

# This scope allows CRUD on all reports in ReportStream for this one organization.
scope = f"{my_client_id}.*.report"

print(
f'''
STEP 3:  Send that signed JWT to ReportStream, to get a temporary bearer token

EXAMPLE: Here is an example curl call to request a submission token valid only for the next 5 minutes, using this JWT.
This assumes you have already given your public key to ReportStream.  Note that with the -d option, the parameters are sent in the message body.

curl{exe} -X POST -H "Content-Type: application/x-www-form-urlencoded"  -d "scope={scope}&grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion={token}" "https://staging.prime.cdc.gov/api/token"

If its working, you'll get back a response like this:

{{"sub":"{my_client_id}.report_90ffad77-9b47-448f-ab51-9b40c856d878","access_token":"ACCESS-TOKEN-STRING-HERE","token_type":"bearer","expires_in":300,"expires_at_seconds":1660744830,"scope":"{scope}"}}

(Note that the scope requested is {scope})

STEP 4: Submit data to ReportStream using the bearer token

EXAMPLE: Here is an example submitting an HL7 2.5.1 payload:

curl{exe} -X POST -H "authorization:bearer ACCESS-TOKEN-STRING-HERE" -H "client:{my_client_id}"  -H "content-type:application/hl7-v2" --data-binary "@.{os.sep}my-nonPII-data.hl7" "https://staging.prime.cdc.gov/api/waters"



''')
