FROM node:14-alpine

WORKDIR /app

# Directories
COPY ./public /app/public
COPY ./src /app/src

# Root files
COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock
COPY ./tsconfig.json /app/tsconfig.json
COPY ./craco.config.js /app/craco.config.js

RUN [ "yarn", "install" ]
RUN [ "yarn", "add", "eslint-config-react-app", "-D" ]

ENV NODE_ENV=development
EXPOSE 3000
ENTRYPOINT [ "npm", "start" ]