export const mockAdminAction: AdminAction = {
    actionId: 0,
    actionName: "action",
    createdAt: "2022-07-11T00:00:00.001Z",
    httpStatus: 200,
    actionParams: "",
    actionResult: "",
    actionResponse: "",
    contentLength: 101,
    senderIp: "",
    sendingOrg: "",
    sendingOrgClient: "",
    externalName: "",
    username: "",
};

export const mockSendFailure: SendFailure = {
    actionId: 0,
    reportId: "",
    receiver: "",
    fileName: "",
    failedAt: "",
    actionParams: "",
    actionResult: "",
    bodyUrl: "",
    reportFileReceiver: "",
};

export const mockReceiverConnectionStatus: ReceiverConnectionStatus = {
    receiverConnectionCheckResultId: 2397,
    organizationId: 61,
    receiverId: 313,
    connectionCheckResult: "connectionCheckResult dummy result 2397",
    connectionCheckSuccessful: true,
    connectionCheckStartedAt: "2022-07-11T00:00:00.001Z",
    connectionCheckCompletedAt: "2022-07-11T00:00:50.000Z",
    organizationName: "ca-dph",
    receiverName: "elr",
};

export const mockReceiverConnectionStatuses: ReceiverConnectionStatus[] = [
    {
        receiverConnectionCheckResultId: 2397,
        organizationId: 61,
        receiverId: 313,
        connectionCheckResult: "connectionCheckResult dummy result 2397",
        connectionCheckSuccessful: true,
        connectionCheckStartedAt: "2022-07-11T00:00:00.001Z",
        connectionCheckCompletedAt: "2022-07-11T00:00:50.000Z",
        organizationName: "ca-dph",
        receiverName: "elr",
    },
    {
        receiverConnectionCheckResultId: 2398,
        organizationId: 61,
        receiverId: 313,
        connectionCheckResult: "connectionCheckResult dummy result 2398",
        connectionCheckSuccessful: true,
        connectionCheckStartedAt: "2022-07-11T07:59:24.036Z",
        connectionCheckCompletedAt: "2022-07-11T07:59:24.358Z",
        organizationName: "ca-dph",
        receiverName: "elr-secondary",
    },
    {
        receiverConnectionCheckResultId: 2399,
        organizationId: 49,
        receiverId: 311,
        connectionCheckResult: "connectionCheckResult dummy result 2399",
        connectionCheckSuccessful: true,
        connectionCheckStartedAt: "2022-07-11T07:59:23.713Z",
        connectionCheckCompletedAt: "2022-07-11T07:59:24.033Z",
        organizationName: "oh-doh",
        receiverName: "elr",
    },
    {
        // this entry is out-of-sort-order and connectionCheckSuccessful:failed
        receiverConnectionCheckResultId: 2396,
        organizationId: 61,
        receiverId: 312,
        connectionCheckResult: "connectionCheckResult dummy result 2396",
        connectionCheckSuccessful: false,
        connectionCheckStartedAt: "2022-07-11T07:59:23.385Z",
        connectionCheckCompletedAt: "2022-07-11T07:59:23.711Z",
        organizationName: "ca-dph",
        receiverName: "elr",
    },
    {
        receiverConnectionCheckResultId: 2395,
        organizationId: 46,
        receiverId: 310,
        connectionCheckResult: "connectionCheckResult dummy result 2395",
        connectionCheckSuccessful: true,
        connectionCheckStartedAt: "2022-07-11T08:09:23.066Z",
        connectionCheckCompletedAt: "2022-07-11T08:09:23.383Z",
        organizationName: "vt-doh",
        receiverName: "elr-otc",
    },
    {
        receiverConnectionCheckResultId: 2394,
        organizationId: 46,
        receiverId: 309,
        connectionCheckResult: "connectionCheckResult dummy result 2394",
        connectionCheckSuccessful: false,
        connectionCheckStartedAt: "2022-07-11T08:09:22.748Z",
        connectionCheckCompletedAt: "2022-07-11T08:09:23.063Z",
        organizationName: "vt-doh",
        receiverName: "elr-secondary",
    },
];
