// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
    DeleteEmailScheduleByScheduleIdResponse,
    DeleteSettingsOrganizationsByOrganizationNameData,
    DeleteSettingsOrganizationsByOrganizationNamePublicKeysByScopeByKidData,
    DeleteSettingsOrganizationsByOrganizationNamePublicKeysByScopeByKidResponse,
    DeleteSettingsOrganizationsByOrganizationNameReceiversByReceiverNameData,
    DeleteSettingsOrganizationsByOrganizationNameReceiversByReceiverNameResponse,
    DeleteSettingsOrganizationsByOrganizationNameResponse,
    DeleteSettingsOrganizationsByOrganizationNameSendersBySenderNameData,
    DeleteSettingsOrganizationsByOrganizationNameSendersBySenderNameResponse,
    GetCheckResponse,
    GetDeliveriesData,
    GetDeliveriesResponse,
    GetDeliveryDetailsData,
    GetDeliveryDetailsResponse,
    GetDeliveryEtorMetadataData,
    GetDeliveryEtorMetadataResponse,
    GetDeliveryFacilitiesData,
    GetDeliveryFacilitiesResponse,
    GetEtorMetadataForHistoryData,
    GetEtorMetadataForHistoryResponse,
    GetListReceiversConnStatusData,
    GetListReceiversConnStatusResponse,
    GetLookuptablesByTableNameByTableVersionContentData,
    GetLookuptablesByTableNameByTableVersionContentResponse,
    GetLookuptablesByTableNameByTableVersionInfoData,
    GetLookuptablesByTableNameByTableVersionInfoResponse,
    GetLookuptablesByTableNameContentData,
    GetLookuptablesByTableNameContentResponse,
    GetLookuptablesListData,
    GetLookuptablesListResponse,
    GetMessageByIdData,
    GetMessageByIdResponse,
    GetMessagesData,
    GetMessagesResponse,
    GetMetadataLivdResponse,
    GetResendData,
    GetResendResponse,
    GetSaveTestDataResponse,
    GetSenderFilesData,
    GetSenderFilesResponse,
    GetSendFailuresData,
    GetSendFailuresResponse,
    GetSettingsOrganizationsByOrganizationNameData,
    GetSettingsOrganizationsByOrganizationNamePublicKeysData,
    GetSettingsOrganizationsByOrganizationNamePublicKeysResponse,
    GetSettingsOrganizationsByOrganizationNameReceiversByReceiverNameData,
    GetSettingsOrganizationsByOrganizationNameReceiversByReceiverNameResponse,
    GetSettingsOrganizationsByOrganizationNameReceiversData,
    GetSettingsOrganizationsByOrganizationNameReceiversResponse,
    GetSettingsOrganizationsByOrganizationNameResponse,
    GetSettingsOrganizationsByOrganizationNameSendersBySenderNameData,
    GetSettingsOrganizationsByOrganizationNameSendersBySenderNameResponse,
    GetSettingsOrganizationsByOrganizationNameSendersData,
    GetSettingsOrganizationsByOrganizationNameSendersResponse,
    GetSettingsOrganizationsResponse,
    GetSubmissionsData,
    GetSubmissionsResponse,
    GetSubmissionsSubmissionByActionidData,
    GetSubmissionsSubmissionByActionidResponse,
    GetWatersOrgByOrganizationBySenderChannelSubmissionsData,
    GetWatersOrgByOrganizationBySenderChannelSubmissionsResponse,
    GetWatersOrgByOrganizationDeliveriesData,
    GetWatersOrgByOrganizationDeliveriesResponse,
    GetWatersOrgByOrganizationNameSendersRevsBySettingTypeData,
    GetWatersOrgByOrganizationNameSendersRevsBySettingTypeResponse,
    GetWatersOrgByOrganizationSubmissionsData,
    GetWatersOrgByOrganizationSubmissionsResponse,
    GetWatersReportByIdHistoryData,
    GetWatersReportByIdHistoryResponse,
    HeadSettingsOrganizationsResponse,
    PostCheckreceiverOrgByOrgNameReceiverByReceiverNameData,
    PostCheckreceiverOrgByOrgNameReceiverByReceiverNameResponse,
    PostEmailRegisteredResponse,
    PostEmailScheduleResponse,
    PostLookuptablesByTableNameData,
    PostLookuptablesByTableNameResponse,
    PostReportsData,
    PostReportsResponse,
    PostRequeueSendData,
    PostRequeueSendResponse,
    PostSettingsOrganizationsByOrganizationNamePublicKeysData,
    PostSettingsOrganizationsByOrganizationNamePublicKeysResponse,
    PostTokenData,
    PostTokenResponse,
    PostValidateData,
    PostValidateResponse,
    PostWatersReportsData,
    PostWatersReportsResponse,
    PutLookuptablesByTableNameByTableVersionActivateData,
    PutLookuptablesByTableNameByTableVersionActivateResponse,
    PutSettingsOrganizationsByOrganizationNameData,
    PutSettingsOrganizationsByOrganizationNameReceiversByReceiverNameData,
    PutSettingsOrganizationsByOrganizationNameReceiversByReceiverNameResponse,
    PutSettingsOrganizationsByOrganizationNameResponse,
    PutSettingsOrganizationsByOrganizationNameSendersBySenderNameData,
    PutSettingsOrganizationsByOrganizationNameSendersBySenderNameResponse,
    SearchReceiverDeliveriesData,
    SearchReceiverDeliveriesResponse,
    SearchReceiverSubmittersData,
    SearchReceiverSubmittersResponse,
} from "./types.gen";

export class DefaultService {
    /**
     * returns a list of simple submissions for a specific sender
     * @param data The data for the request.
     * @param data.organization sender of the report history we want to look at
     * @param data.sortdir direction in which to sort reports
     * @param data.sortcol column used as the basis for sorting
     * @param data.cursor used by cursor-based pagination to determine the position on the results
     * @param data.since only return results from after the given date
     * @param data.until only return results from before the given date
     * @param data.pagesize number of results per page
     * @param data.showFailed whether or not to show submissions that failed delivery
     * @returns SubmissionHistoryList a list of submission history objects
     * @throws ApiError
     */
    public static getWatersOrgByOrganizationSubmissions(
        data: GetWatersOrgByOrganizationSubmissionsData,
    ): CancelablePromise<GetWatersOrgByOrganizationSubmissionsResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/org/{organization}/submissions",
            path: {
                organization: data.organization,
            },
            query: {
                sortdir: data.sortdir,
                sortcol: data.sortcol,
                cursor: data.cursor,
                since: data.since,
                until: data.until,
                pagesize: data.pagesize,
                showFailed: data.showFailed,
            },
            errors: {
                400: "bad request",
            },
        });
    }

    /**
     * returns a list of simple submissions for a specific sender and sender channel
     * @param data The data for the request.
     * @param data.organization sender of the report history we want to look at
     * @param data.senderChannel sender channel of the report history we want to look at
     * @param data.sortdir direction in which to sort reports
     * @param data.sortcol column used as the basis for sorting
     * @param data.cursor used by cursor-based pagination to determine the position on the results
     * @param data.since only return results from after the given date
     * @param data.until only return results from before the given date
     * @param data.pagesize number of results per page
     * @param data.showFailed whether or not to show submissions that failed delivery
     * @returns SubmissionHistoryList a list of submission history objects
     * @throws ApiError
     */
    public static getWatersOrgByOrganizationBySenderChannelSubmissions(
        data: GetWatersOrgByOrganizationBySenderChannelSubmissionsData,
    ): CancelablePromise<GetWatersOrgByOrganizationBySenderChannelSubmissionsResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/org/{organization}.{senderChannel}/submissions",
            path: {
                organization: data.organization,
                senderChannel: data.senderChannel,
            },
            query: {
                sortdir: data.sortdir,
                sortcol: data.sortcol,
                cursor: data.cursor,
                since: data.since,
                until: data.until,
                pagesize: data.pagesize,
                showFailed: data.showFailed,
            },
            errors: {
                400: "bad request",
            },
        });
    }

    /**
     * submit a report to be routed
     * @param data The data for the request.
     * @param data.requestBody The public health information being routed
     * @param data.processing flag for processing the report in a different manner
     * @returns DetailedSubmissionHistory the detailed report history object
     * @throws ApiError
     */
    public static postWatersReports(
        data: PostWatersReportsData,
    ): CancelablePromise<PostWatersReportsResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/waters/reports",
            query: {
                processing: data.processing,
            },
            body: data.requestBody,
            mediaType: "text/csv",
            errors: {
                401: "unknown or invalid sender",
            },
        });
    }

    /**
     * return detailed history of a single submitted report
     * @param data The data for the request.
     * @param data.id a valid UUID or actionId (aka submissionId)
     * @returns DetailedSubmissionHistory the detailed report history object
     * @throws ApiError
     */
    public static getWatersReportByIdHistory(
        data: GetWatersReportByIdHistoryData,
    ): CancelablePromise<GetWatersReportByIdHistoryResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/report/{id}/history",
            path: {
                id: data.id,
            },
            errors: {
                401: "unauthorized",
                404: "either there is no report with the given id or the report is not a submission",
                500: "unable to fetch history due to Data Access Exception",
            },
        });
    }

    /**
     * Get available reports for all org STLTs
     * Retrieve a list of reports available for download by a STLT
     * @param data The data for the request.
     * @param data.organization receiver whose deliveries we want to see
     * @param data.reportId the reportId within the deliveries of the organization and client
     * @param data.fileName the fileName within the deliveries of the organization and client
     * @param data.receivingOrgSvcStatus Customer status of the service used by the organization. Can append the parameter multiple times for more than one status.
     * @param data.sortdir direction in which to sort reports
     * @param data.sortcol column used as the basis for sorting
     * @param data.cursor used by cursor-based pagination to determine the position on the results
     * @param data.since only return results from after the given date
     * @param data.until only return results from before the given date
     * @param data.pagesize number of results per page
     * @returns Deliveries a list of AvailableReport objects
     * @throws ApiError
     */
    public static getWatersOrgByOrganizationDeliveries(
        data: GetWatersOrgByOrganizationDeliveriesData,
    ): CancelablePromise<GetWatersOrgByOrganizationDeliveriesResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/org/{organization}/deliveries",
            path: {
                organization: data.organization,
            },
            query: {
                reportId: data.reportId,
                fileName: data.fileName,
                receivingOrgSvcStatus: data.receivingOrgSvcStatus,
                sortdir: data.sortdir,
                sortcol: data.sortcol,
                cursor: data.cursor,
                since: data.since,
                until: data.until,
                pagesize: data.pagesize,
            },
            errors: {
                400: "bad request",
                401: "unauthorized",
                404: "organization does not exist",
            },
        });
    }

    /**
     * Get available reports for a STLT
     * Retrieve a list of reports available for download by a STLT
     * @param data The data for the request.
     * @param data.organization receiver whose deliveries we want to see
     * @param data.client client of the receiver to get deliveries for
     * @param data.reportId the reportId within the deliveries of the organization and client
     * @param data.fileName the fileName within the deliveries of the organization and client
     * @param data.receivingOrgSvcStatus Customer status of the service used by the organization. Can append the parameter multiple times for more than one status.
     * @param data.sortdir direction in which to sort reports
     * @param data.sortcol column used as the basis for sorting
     * @param data.cursor used by cursor-based pagination to determine the position on the results
     * @param data.since only return results from after the given date
     * @param data.until only return results from before the given date
     * @param data.pagesize number of results per page
     * @returns Deliveries a list of AvailableReport objects
     * @throws ApiError
     */
    public static getDeliveries(
        data: GetDeliveriesData,
    ): CancelablePromise<GetDeliveriesResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/org/{organization}.{client}/deliveries",
            path: {
                organization: data.organization,
                client: data.client,
            },
            query: {
                reportId: data.reportId,
                fileName: data.fileName,
                receivingOrgSvcStatus: data.receivingOrgSvcStatus,
                sortdir: data.sortdir,
                sortcol: data.sortcol,
                cursor: data.cursor,
                since: data.since,
                until: data.until,
                pagesize: data.pagesize,
            },
            errors: {
                400: "bad request",
                401: "unauthorized",
                404: "organization does not exist",
            },
        });
    }

    /**
     * Get expanded details for a single report
     * Retrieve the details for a report, including easily fetched relations
     * @param data The data for the request.
     * @param data.id ActionID or ReportId of report whose details we want to see
     * @returns Delivery a report detail object
     * @throws ApiError
     */
    public static getDeliveryDetails(
        data: GetDeliveryDetailsData,
    ): CancelablePromise<GetDeliveryDetailsResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/report/{id}/delivery",
            path: {
                id: data.id,
            },
            errors: {
                400: "bad request",
                401: "unauthorized",
                404: "report does not exist",
            },
        });
    }

    /**
     * Get facilities for a single report
     * Retrieve the list of facilities for a report
     * @param data The data for the request.
     * @param data.id ActionID or ReportId of report whose facilities we want to see
     * @param data.sortdir direction in which to sort reports
     * @param data.sortcol column used as the basis for sorting
     * @returns FacilitiesList an array of facilities in the report
     * @throws ApiError
     */
    public static getDeliveryFacilities(
        data: GetDeliveryFacilitiesData,
    ): CancelablePromise<GetDeliveryFacilitiesResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/report/{id}/facilities",
            path: {
                id: data.id,
            },
            query: {
                sortdir: data.sortdir,
                sortcol: data.sortcol,
            },
            errors: {
                400: "bad request",
                401: "unauthorized",
                404: "report does not exist",
            },
        });
    }

    /**
     * Validate a message using client information. Validation errors and warnings are reported in the response json.
     * @param data The data for the request.
     * @param data.requestBody The message to validate
     * @param data.client The client.sender to validate against. If client is not known, use `schema` and `format` instead.
     * @param data.schema The schema path to validate the message against. Must be use with `format`. This parameter is incompatible with `client`.
     *
     * @param data.format The format of the message. must be used with `schema`.  This parameter is incompatible with `client`.
     *
     * @returns Report OK
     * @throws ApiError
     */
    public static postValidate(
        data: PostValidateData,
    ): CancelablePromise<PostValidateResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/validate",
            headers: {
                client: data.client,
            },
            query: {
                schema: data.schema,
                format: data.format,
            },
            body: data.requestBody,
            mediaType: "text/csv",
            errors: {
                400: "Bad Request",
            },
        });
    }

    /**
     * Generate and return a new token for the requested scope
     * @param data The data for the request.
     * @param data.formData Parameters should be sent in the request body.
     * @returns TableVersionInfo the token was created and returned
     * @throws ApiError
     */
    public static postToken(
        data: PostTokenData,
    ): CancelablePromise<PostTokenResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "token",
            formData: data.formData,
            mediaType: "application/x-www-form-urlencoded",
            errors: {
                400: "bad request",
                401: "unauthorized",
            },
        });
    }

    /**
     * Return a list of all basic info on all receive actions and associated reports.
     * @param data The data for the request.
     * @param data.pagesize The number of items to return (default `10`).
     * @param data.sort Orders by created date time, this controls if it is asc or desc (default 'desc')
     * @param data.cursor The cursor pointing to the next portion of results. If you don't pass a `cursor` parameter, but **do** pass a `limit` parameter, the default value retrieves the first portion of results. Paginated responses include a `response_metadata` object that includes a `next_cursor` *when there are additional results to be retrieved.* On your next call to the same method, set the `cursor` parameter equal to the `next_cursor` value you received on the last request to retrieve the next portion of the collection. An empty, null, or non-existent `next_cursor` in the response indicates no further results.
     * @param data.dateStart (`YYYY-MM-DD`) Start date to get results for.
     * @param data.dateEnd (`YYYY-MM-DD') End date to get results for.
     * @param data.year (`YYYY` - default `ALL`) Return results from specific Year, overriden by start/end
     * @param data.month (`MM` - default `ALL`) Return results from specific Month. Requires `year` being set. Overriden by start/end
     * @param data.organizations (`{INT, INT, INT}` || `INT` - default `ALL`) Return results from specific Organization or array of Organizations. Must have admin access.
     * @param data.recipients (`{INT, INT, INT}` || `INT` - default `ALL`) Return results from specific Recipient or array of Recipients.
     * @param data.senders (`{INT, INT, INT}`  || `INT` - default `ALL`) Return results from specific Sender or array of Senders.
     * @param data.warnings (`ALL` || `WITH` || `WITHOUT` - default `ALL`) If `WITH` only return results with Warning(s). If `WITHOUT` only results without Warning(s).
     * @param data.errors (`ALL` || `WITH` || `WITHOUT` - default `ALL`) If `WITH` only return results with Error(s). If `WITHOUT` only results without Error(s).
     * @param data.receipts (`ALL` || `WITH` || `WITHOUT` - default `ALL`) If `WITH` only return results with Receipt(s). If `WITHOUT` only results without Receipt(s).
     * @returns History OK
     * @throws ApiError
     */
    public static getSubmissions(
        data: GetSubmissionsData,
    ): CancelablePromise<GetSubmissionsResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/submissions",
            query: {
                cursor: data.cursor,
                pagesize: data.pagesize,
                sort: data.sort,
                dateStart: data.dateStart,
                dateEnd: data.dateEnd,
                year: data.year,
                month: data.month,
                organizations: data.organizations,
                recipients: data.recipients,
                senders: data.senders,
                warnings: data.warnings,
                errors: data.errors,
                receipts: data.receipts,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * Return a single receive action, and its received report(s), or an error report.
     * @param data The data for the request.
     * @param data.actionid The `actionID` for a single receiver action.
     * @returns Submission OK
     * @throws ApiError
     */
    public static getSubmissionsSubmissionByActionid(
        data: GetSubmissionsSubmissionByActionidData,
    ): CancelablePromise<GetSubmissionsSubmissionByActionidResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/submissions/submission/{actionid}",
            path: {
                actionid: data.actionid,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
                500: "Internal Server Error",
            },
        });
    }

    /**
     * Retrieves ETOR metadata for a sender's report
     * Fetches the ETOR intermediary's metadata given the sender's report ID.
     * @param data The data for the request.
     * @param data.reportId The unique identifier of the report.
     * @returns OperationOutcome Successful retrieval of ETOR metadata.
     * @throws ApiError
     */
    public static getEtorMetadataForHistory(
        data: GetEtorMetadataForHistoryData,
    ): CancelablePromise<GetEtorMetadataForHistoryResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/report/{reportId}/history/etorMetadata",
            path: {
                reportId: data.reportId,
            },
            errors: {
                404: "lookup Id not found",
                500: "Internal server error.",
            },
        });
    }

    /**
     * The settings for all organizations of the system. Must have admin access.
     * @returns Organization1 OK
     * @throws ApiError
     */
    public static getSettingsOrganizations(): CancelablePromise<GetSettingsOrganizationsResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/settings/organizations",
        });
    }

    /**
     * Retrieved the last modified for all settings of the system. Must have admin access.
     * @returns string OK
     * @throws ApiError
     */
    public static headSettingsOrganizations(): CancelablePromise<HeadSettingsOrganizationsResponse> {
        return __request(OpenAPI, {
            method: "HEAD",
            url: "/settings/organizations",
            responseHeader: "Last-Modified",
        });
    }

    /**
     * A single organization settings
     * @param data The data for the request.
     * @param data.organizationName The name of the organization
     * @returns Organization1 OK
     * @throws ApiError
     */
    public static getSettingsOrganizationsByOrganizationName(
        data: GetSettingsOrganizationsByOrganizationNameData,
    ): CancelablePromise<GetSettingsOrganizationsByOrganizationNameResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/settings/organizations/{organizationName}",
            path: {
                organizationName: data.organizationName,
            },
        });
    }

    /**
     * Create or update the direct settings associated with an organization
     * @param data The data for the request.
     * @param data.organizationName The name of the organization
     * @param data.requestBody
     * @returns Organization1 OK, the organization setting was updated
     * @throws ApiError
     */
    public static putSettingsOrganizationsByOrganizationName(
        data: PutSettingsOrganizationsByOrganizationNameData,
    ): CancelablePromise<PutSettingsOrganizationsByOrganizationNameResponse> {
        return __request(OpenAPI, {
            method: "PUT",
            url: "/settings/organizations/{organizationName}",
            path: {
                organizationName: data.organizationName,
            },
            body: data.requestBody,
            mediaType: "application/json",
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * Delete an organization (and the associated receivers and senders)
     * @param data The data for the request.
     * @param data.organizationName The name of the organization
     * @returns Organization1 OK, the organization setting was deleted
     * @throws ApiError
     */
    public static deleteSettingsOrganizationsByOrganizationName(
        data: DeleteSettingsOrganizationsByOrganizationNameData,
    ): CancelablePromise<DeleteSettingsOrganizationsByOrganizationNameResponse> {
        return __request(OpenAPI, {
            method: "DELETE",
            url: "/settings/organizations/{organizationName}",
            path: {
                organizationName: data.organizationName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * A list of receivers and their current settings
     * @param data The data for the request.
     * @param data.organizationName Fetch receivers with this organization name
     * @returns Receiver OK
     * @throws ApiError
     */
    public static getSettingsOrganizationsByOrganizationNameReceivers(
        data: GetSettingsOrganizationsByOrganizationNameReceiversData,
    ): CancelablePromise<GetSettingsOrganizationsByOrganizationNameReceiversResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/settings/organizations/{organizationName}/receivers",
            path: {
                organizationName: data.organizationName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * The settings of a single of receiver
     * @param data The data for the request.
     * @param data.organizationName Create receivers under this organization name
     * @param data.receiverName The name of the receiver
     * @returns Receiver OK
     * @throws ApiError
     */
    public static getSettingsOrganizationsByOrganizationNameReceiversByReceiverName(
        data: GetSettingsOrganizationsByOrganizationNameReceiversByReceiverNameData,
    ): CancelablePromise<GetSettingsOrganizationsByOrganizationNameReceiversByReceiverNameResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/settings/organizations/{organizationName}/receivers/{receiverName}",
            path: {
                organizationName: data.organizationName,
                receiverName: data.receiverName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * Update a single receiver
     * @param data The data for the request.
     * @param data.organizationName Create receivers under this organization name
     * @param data.receiverName The name of the receiver
     * @param data.requestBody
     * @returns Receiver OK, the receiver setting was updated
     * @throws ApiError
     */
    public static putSettingsOrganizationsByOrganizationNameReceiversByReceiverName(
        data: PutSettingsOrganizationsByOrganizationNameReceiversByReceiverNameData,
    ): CancelablePromise<PutSettingsOrganizationsByOrganizationNameReceiversByReceiverNameResponse> {
        return __request(OpenAPI, {
            method: "PUT",
            url: "/settings/organizations/{organizationName}/receivers/{receiverName}",
            path: {
                organizationName: data.organizationName,
                receiverName: data.receiverName,
            },
            body: data.requestBody,
            mediaType: "application/json",
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * Delete a receiver
     * @param data The data for the request.
     * @param data.organizationName the organization name
     * @param data.receiverName The name of the receiver
     * @returns Receiver OK, the receiver was deleted
     * @throws ApiError
     */
    public static deleteSettingsOrganizationsByOrganizationNameReceiversByReceiverName(
        data: DeleteSettingsOrganizationsByOrganizationNameReceiversByReceiverNameData,
    ): CancelablePromise<DeleteSettingsOrganizationsByOrganizationNameReceiversByReceiverNameResponse> {
        return __request(OpenAPI, {
            method: "DELETE",
            url: "/settings/organizations/{organizationName}/receivers/{receiverName}",
            path: {
                organizationName: data.organizationName,
                receiverName: data.receiverName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * A list of senders
     * @param data The data for the request.
     * @param data.organizationName Fetch senders with this organization name
     * @returns Sender OK
     * @throws ApiError
     */
    public static getSettingsOrganizationsByOrganizationNameSenders(
        data: GetSettingsOrganizationsByOrganizationNameSendersData,
    ): CancelablePromise<GetSettingsOrganizationsByOrganizationNameSendersResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/settings/organizations/{organizationName}/senders",
            path: {
                organizationName: data.organizationName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * The settings of a single of sender
     * @param data The data for the request.
     * @param data.organizationName Fetch senders with this organization name
     * @param data.senderName The name of a sender to the data hub
     * @returns Sender OK
     * @throws ApiError
     */
    public static getSettingsOrganizationsByOrganizationNameSendersBySenderName(
        data: GetSettingsOrganizationsByOrganizationNameSendersBySenderNameData,
    ): CancelablePromise<GetSettingsOrganizationsByOrganizationNameSendersBySenderNameResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/settings/organizations/{organizationName}/senders/{senderName}",
            path: {
                organizationName: data.organizationName,
                senderName: data.senderName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * Update a single sender
     * @param data The data for the request.
     * @param data.organizationName Fetch senders with this organization name
     * @param data.senderName The name of a sender to the data hub
     * @param data.requestBody
     * @returns Sender OK
     * @throws ApiError
     */
    public static putSettingsOrganizationsByOrganizationNameSendersBySenderName(
        data: PutSettingsOrganizationsByOrganizationNameSendersBySenderNameData,
    ): CancelablePromise<PutSettingsOrganizationsByOrganizationNameSendersBySenderNameResponse> {
        return __request(OpenAPI, {
            method: "PUT",
            url: "/settings/organizations/{organizationName}/senders/{senderName}",
            path: {
                organizationName: data.organizationName,
                senderName: data.senderName,
            },
            body: data.requestBody,
            mediaType: "application/json",
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * Delete a sender
     * @param data The data for the request.
     * @param data.organizationName the organization name
     * @param data.senderName The name of a sender to the data hub
     * @returns Sender OK, the sender was deleted
     * @throws ApiError
     */
    public static deleteSettingsOrganizationsByOrganizationNameSendersBySenderName(
        data: DeleteSettingsOrganizationsByOrganizationNameSendersBySenderNameData,
    ): CancelablePromise<DeleteSettingsOrganizationsByOrganizationNameSendersBySenderNameResponse> {
        return __request(OpenAPI, {
            method: "DELETE",
            url: "/settings/organizations/{organizationName}/senders/{senderName}",
            path: {
                organizationName: data.organizationName,
                senderName: data.senderName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * The full history of setting revisions for all settings of a given type.
     * @param data The data for the request.
     * @param data.organizationName Fetch senders with this organization name
     * @param data.settingType Type of setting
     * @returns SettingRevisions OK
     * @throws ApiError
     */
    public static getWatersOrgByOrganizationNameSendersRevsBySettingType(
        data: GetWatersOrgByOrganizationNameSendersRevsBySettingTypeData,
    ): CancelablePromise<GetWatersOrgByOrganizationNameSendersRevsBySettingTypeResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/org/{organizationName}/senders/revs/{settingType}",
            path: {
                organizationName: data.organizationName,
                settingType: data.settingType,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
            },
        });
    }

    /**
     * For a specified report, trace each item's ancestry and retrieve the source files submitted by senders.
     * @param data The data for the request.
     * @param data.reportId Report-id (uuid format) of the receiver report
     * @param data.reportFileName File name of the receiver report
     * @param data.offset The offset into the receiver report for the first item
     * @param data.limit The maximum number of receiver items to retrieve
     * @param data.onlyReportItems Only include items in the sender file that route to the receiver report
     * @returns ReportFileMessage A list of the sender files associated with the specified receiver report.
     * @throws ApiError
     */
    public static getSenderFiles(
        data: GetSenderFilesData = {},
    ): CancelablePromise<GetSenderFilesResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/sender-files",
            query: {
                "report-id": data.reportId,
                "report-file-name": data.reportFileName,
                offset: data.offset,
                limit: data.limit,
                "only-report-items": data.onlyReportItems,
            },
        });
    }

    /**
     * manually queue up a report to be sent again to one receiver
     * @param data The data for the request.
     * @param data.reportId UUID for the report to resend
     * @param data.receiver full name of the receiver to resend the report to
     * @param data.requestBody Empty body due to the POST format
     * @param data.test if given, includes additional debug messages
     * @returns RequeueResponse text stating how many items in the report will be resent
     * @throws ApiError
     */
    public static postRequeueSend(
        data: PostRequeueSendData,
    ): CancelablePromise<PostRequeueSendResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/requeue/send",
            query: {
                reportId: data.reportId,
                receiver: data.receiver,
                test: data.test,
            },
            body: data.requestBody,
            mediaType: "application/json",
            errors: {
                400: "bad request",
            },
        });
    }

    /**
     * Post a report to the data hub
     * @param data The data for the request.
     * @param data.client The client's name that matches the client name in metadata
     * @param data.requestBody The public health information being routed
     * @param data.option Optional ways to process the request
     * @param data._default Dynamic default values for an element. ':' or : is used to seperate element name and value
     * @param data.routeTo A comma separated list of receiver names. Limit the list of possible receivers to these receivers.
     * @param data.processing 'sync' or 'async'. defaults to 'sync'. Determines if the incoming message will follow the sync or async process
     * @param data.payloadName Optional string name for the data payload submitted.   Typically a filename or other name useful to the sender's record-keeping.  Tracked, but not used, by ReportStream.  Must never include PII/PHI.
     * @returns Report OK
     * @throws ApiError
     */
    public static postReports(
        data: PostReportsData,
    ): CancelablePromise<PostReportsResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/reports",
            query: {
                client: data.client,
                option: data.option,
                default: data._default,
                routeTo: data.routeTo,
                processing: data.processing,
                payloadName: data.payloadName,
            },
            body: data.requestBody,
            mediaType: "text/csv",
            errors: {
                400: "Invalid request. No report created.",
                500: "Internal Server Error",
            },
        });
    }

    /**
     * get data from LIVD tables
     * @returns unknown success
     * @throws ApiError
     */
    public static getMetadataLivd(): CancelablePromise<GetMetadataLivdResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/metadata/livd",
        });
    }

    /**
     * Fetch a list of COVID result entries from the `covid_result_metadata` table based on a `messageId`, called `message_id` on the backend. This endpoint will typically return one result but `message_id` is not guaranteed to be unique, so multiple results can be returned.
     * @param data The data for the request.
     * @param data.messageId The `message_id` of a COVID result message.
     * @returns Message a list of messages
     * @throws ApiError
     */
    public static getMessages(
        data: GetMessagesData,
    ): CancelablePromise<GetMessagesResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/messages",
            query: {
                messageId: data.messageId,
            },
            errors: {
                400: "missing messageId parameter or a bad request",
                401: "unauthorized",
            },
        });
    }

    /**
     * Return details about a particular COVID test result message from the covid_result_metadata table.
     * @param data The data for the request.
     * @param data.id The unique identifier of a COVID test result message, that being the `covid_results_metadata_id` PK of the `covid_result_metadata` table.
     * @returns Message The message details related to COVID test result message.
     * @throws ApiError
     */
    public static getMessageById(
        data: GetMessageByIdData,
    ): CancelablePromise<GetMessageByIdResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/message/{id}",
            path: {
                id: data.id,
            },
            errors: {
                400: "bad request",
                401: "unauthorized",
            },
        });
    }

    /**
     * Fetch the list lookup tables
     * @param data The data for the request.
     * @param data.showInactive Set to true to include inactive tables
     * @returns TableVersionArray The list of tables with version information
     * @throws ApiError
     */
    public static getLookuptablesList(
        data: GetLookuptablesListData = {},
    ): CancelablePromise<GetLookuptablesListResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/lookuptables/list",
            query: {
                showInactive: data.showInactive,
            },
            errors: {
                400: "if there was an error fetching the list of tables",
            },
        });
    }

    /**
     * Create a new version of a lookup table.  First versions of a table are automatically activated.
     * @param data The data for the request.
     * @param data.tableName Name of new lookup table
     * @param data.requestBody An array of objects that list the table's rows.
     * @returns TableVersionInfo The table was created
     * @throws ApiError
     */
    public static postLookuptablesByTableName(
        data: PostLookuptablesByTableNameData,
    ): CancelablePromise<PostLookuptablesByTableNameResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/lookuptables/{tableName}",
            path: {
                tableName: data.tableName,
            },
            body: data.requestBody,
            mediaType: "application/json",
            errors: {
                400: "if there was an error creating the table",
            },
        });
    }

    /**
     * Fetch the contents of a specific version of a table
     * @param data The data for the request.
     * @param data.tableName Name of lookup table
     * @param data.tableVersion Version of specified table
     * @returns DynamicTableRows The table contents
     * @throws ApiError
     */
    public static getLookuptablesByTableNameByTableVersionContent(
        data: GetLookuptablesByTableNameByTableVersionContentData,
    ): CancelablePromise<GetLookuptablesByTableNameByTableVersionContentResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/lookuptables/{tableName}/{tableVersion}/content",
            path: {
                tableName: data.tableName,
                tableVersion: data.tableVersion,
            },
            errors: {
                400: "if there was an error fetching the table data",
                404: "The table name and/or version was not found",
            },
        });
    }

    /**
     * Fetch the contents of the active version of a table
     * @param data The data for the request.
     * @param data.tableName Name of lookup table
     * @returns DynamicTableRows The table contents
     * @throws ApiError
     */
    public static getLookuptablesByTableNameContent(
        data: GetLookuptablesByTableNameContentData,
    ): CancelablePromise<GetLookuptablesByTableNameContentResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/lookuptables/{tableName}/content",
            path: {
                tableName: data.tableName,
            },
            errors: {
                400: "if there was an error fetching the table data",
                404: "The table name was not found, or there was no active version of that table.",
            },
        });
    }

    /**
     * Fetch the version information of a specific version of a table
     * @param data The data for the request.
     * @param data.tableName Name of lookup table
     * @param data.tableVersion Version of specified table
     * @returns TableVersionInfo The table version information
     * @throws ApiError
     */
    public static getLookuptablesByTableNameByTableVersionInfo(
        data: GetLookuptablesByTableNameByTableVersionInfoData,
    ): CancelablePromise<GetLookuptablesByTableNameByTableVersionInfoResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/lookuptables/{tableName}/{tableVersion}/info",
            path: {
                tableName: data.tableName,
                tableVersion: data.tableVersion,
            },
            errors: {
                400: "if there was an error fetching the table data",
                404: "The table name and/or version was not found",
            },
        });
    }

    /**
     * Activate a specific version of a table.  This endpoint does not take a request body.
     * @param data The data for the request.
     * @param data.tableName Name of lookup table
     * @param data.tableVersion Version of specified table
     * @returns TableVersionInfo The table version information
     * @throws ApiError
     */
    public static putLookuptablesByTableNameByTableVersionActivate(
        data: PutLookuptablesByTableNameByTableVersionActivateData,
    ): CancelablePromise<PutLookuptablesByTableNameByTableVersionActivateResponse> {
        return __request(OpenAPI, {
            method: "PUT",
            url: "/lookuptables/{tableName}/{tableVersion}/activate",
            path: {
                tableName: data.tableName,
                tableVersion: data.tableVersion,
            },
            errors: {
                400: "if there was an error fetching the table data",
                404: "The table name and/or version was not found",
            },
        });
    }

    /**
     * send a registration email to an organization
     * @returns unknown success call
     * @throws ApiError
     */
    public static postEmailRegistered(): CancelablePromise<PostEmailRegisteredResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/email-registered",
        });
    }

    /**
     * create email schedule
     * @returns unknown success call
     * @throws ApiError
     */
    public static postEmailSchedule(): CancelablePromise<PostEmailScheduleResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/email-schedule",
        });
    }

    /**
     * delete an inactive email schedule
     * @returns unknown success call
     * @throws ApiError
     */
    public static deleteEmailScheduleByScheduleId(): CancelablePromise<DeleteEmailScheduleByScheduleIdResponse> {
        return __request(OpenAPI, {
            method: "DELETE",
            url: "/email-schedule/{scheduleId}",
        });
    }

    /**
     * Returns a list of reports that have been delivered to the receiver
     * @param data The data for the request.
     * @param data.receiverFullName The full name of the receiver to fetch submitters for
     * @param data.requestBody The search parameters for the request
     * @returns DeliveryApiSearchResults The results from running the search
     * @throws ApiError
     */
    public static searchReceiverDeliveries(
        data: SearchReceiverDeliveriesData,
    ): CancelablePromise<SearchReceiverDeliveriesResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/v1/receivers/{receiverFullName}/deliveries",
            path: {
                receiverFullName: data.receiverFullName,
            },
            body: data.requestBody,
            mediaType: "application/json",
            errors: {
                400: "The search request could not be parsed",
                401: "Unauthorized",
                404: "The receiver could not be found",
            },
        });
    }

    /**
     * Retrieves ETOR metadata for a recipient's report
     * Fetches the ETOR intermediary's metadata given the recipient's report ID.
     * @param data The data for the request.
     * @param data.reportId The unique identifier of the report.
     * @returns OperationOutcome Successful retrieval of ETOR metadata.
     * @throws ApiError
     */
    public static getDeliveryEtorMetadata(
        data: GetDeliveryEtorMetadataData,
    ): CancelablePromise<GetDeliveryEtorMetadataResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/waters/report/{reportId}/delivery/etorMetadata",
            path: {
                reportId: data.reportId,
            },
            errors: {
                404: "lookup Id not found",
                500: "Internal server error.",
            },
        });
    }

    /**
     * Return a list of all the providers, facilities and senders that have sent results to a receiver
     * @param data The data for the request.
     * @param data.receiverFullName The full name of the receiver to fetch submitters for
     * @param data.requestBody The search parameters for the request
     * @returns SubmitterApiSearchResults The results from running the search
     * @throws ApiError
     */
    public static searchReceiverSubmitters(
        data: SearchReceiverSubmittersData,
    ): CancelablePromise<SearchReceiverSubmittersResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/v1/receivers/{receiverFullName}/deliveries/submitters/search",
            path: {
                receiverFullName: data.receiverFullName,
            },
            body: data.requestBody,
            mediaType: "application/json",
            errors: {
                400: "The search request could not be parsed",
                401: "Unauthorized",
                404: "The receiver could not be found",
            },
        });
    }

    /**
     * test data extraction api
     * @returns unknown success call
     * @throws ApiError
     */
    public static getSaveTestData(): CancelablePromise<GetSaveTestDataResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/saveTestData",
        });
    }

    /**
     * checks a single remote connection
     * @returns unknown success call
     * @throws ApiError
     */
    public static getCheck(): CancelablePromise<GetCheckResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/check",
        });
    }

    /**
     * Load Receiver Settings and verifies connecting to the external server works.
     * @param data The data for the request.
     * @param data.orgName Name of Organization.
     * @param data.receiverName Logical name of the Receiver Setting
     * @returns CheckReceiverResponse The table contents
     * @throws ApiError
     */
    public static postCheckreceiverOrgByOrgNameReceiverByReceiverName(
        data: PostCheckreceiverOrgByOrgNameReceiverByReceiverNameData,
    ): CancelablePromise<PostCheckreceiverOrgByOrgNameReceiverByReceiverNameResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/checkreceiver/org/{orgName}/receiver/{receiverName}",
            path: {
                orgName: data.orgName,
                receiverName: data.receiverName,
            },
            errors: {
                404: "The orgName or receiverName  was not found",
            },
        });
    }

    /**
     * Deletes a key
     * @param data The data for the request.
     * @param data.organizationName The name of the organization
     * @param data.scope The scope the key to be deleted is associated with
     * @param data.kid The unique identifier of the key to be deleted
     * @returns ApiKeysResponse OK
     * @throws ApiError
     */
    public static deleteSettingsOrganizationsByOrganizationNamePublicKeysByScopeByKid(
        data: DeleteSettingsOrganizationsByOrganizationNamePublicKeysByScopeByKidData,
    ): CancelablePromise<DeleteSettingsOrganizationsByOrganizationNamePublicKeysByScopeByKidResponse> {
        return __request(OpenAPI, {
            method: "DELETE",
            url: "/settings/organizations/{organizationName}/public-keys/{scope}/{kid}",
            path: {
                organizationName: data.organizationName,
                scope: data.scope,
                kid: data.kid,
            },
            errors: {
                401: "Unauthorized",
                404: "Not Found",
            },
        });
    }

    /**
     * Retrieves all of the API public keys for the organization
     * @param data The data for the request.
     * @param data.organizationName The name of the organization
     * @returns ApiKeysResponse OK
     * @throws ApiError
     */
    public static getSettingsOrganizationsByOrganizationNamePublicKeys(
        data: GetSettingsOrganizationsByOrganizationNamePublicKeysData,
    ): CancelablePromise<GetSettingsOrganizationsByOrganizationNamePublicKeysResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/settings/organizations/{organizationName}/public-keys",
            path: {
                organizationName: data.organizationName,
            },
            errors: {
                400: "Bad Request",
                401: "Unauthorized",
                404: "Not Found",
            },
        });
    }

    /**
     * Adds a key for a specific scope.
     * @param data The data for the request.
     * @param data.organizationName The name of the organization storing this key
     * @param data.scope The scope for this key (currently only orgName.*.report)
     * @param data.kid The key id identifying the public key; must be unique for the keys already added for the scope
     * @returns ApiKeysResponse OK
     * @throws ApiError
     */
    public static postSettingsOrganizationsByOrganizationNamePublicKeys(
        data: PostSettingsOrganizationsByOrganizationNamePublicKeysData,
    ): CancelablePromise<PostSettingsOrganizationsByOrganizationNamePublicKeysResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/settings/organizations/{organizationName}/public-keys",
            path: {
                organizationName: data.organizationName,
            },
            query: {
                scope: data.scope,
                kid: data.kid,
            },
            errors: {
                400: "Bad Request. Returned if the scope is not valid, the kid already exists for the scope or the POST body was empty",
                401: "Unauthorized",
                404: "Not Found",
            },
        });
    }

    /**
     * Returns list of recent failed report-forwarding sends. Used to resend failures. Prime admin only.
     * @param data The data for the request.
     * @param data.daysToShow Number of days back from today include in results
     * @returns ListSendFailures OK
     * @throws ApiError
     */
    public static getSendFailures(
        data: GetSendFailuresData = {},
    ): CancelablePromise<GetSendFailuresResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/adm/getsendfailures",
            query: {
                days_to_show: data.daysToShow,
            },
        });
    }

    /**
     * Returns list of recent failed report-forwarding sends. Used to resend failures. Prime admin only.
     * @param data The data for the request.
     * @param data.daysToShow Number of days back from today include in results
     * @returns ListResends OK
     * @throws ApiError
     */
    public static getResend(
        data: GetResendData = {},
    ): CancelablePromise<GetResendResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/adm/getresend",
            query: {
                days_to_show: data.daysToShow,
            },
        });
    }

    /**
     * Get recent report-forward sends across all orgs. Prime admin only.
     * @param data The data for the request.
     * @param data.startDate Date/time for the start range of matches
     * @param data.endDate Optional date/time for the end range of matches
     * @returns ReceiversConnStatusResponse OK
     * @throws ApiError
     */
    public static getListReceiversConnStatus(
        data: GetListReceiversConnStatusData,
    ): CancelablePromise<GetListReceiversConnStatusResponse> {
        return __request(OpenAPI, {
            method: "GET",
            url: "/adm/listreceiversconnstatus",
            query: {
                start_date: data.startDate,
                end_date: data.endDate,
            },
        });
    }
}

export class ValidateService {
    /**
     * Validate a message using client information. Validation errors and warnings are reported in the response json.
     * @param data The data for the request.
     * @param data.requestBody The message to validate
     * @param data.client The client.sender to validate against. If client is not known, use `schema` and `format` instead.
     * @param data.schema The schema path to validate the message against. Must be use with `format`. This parameter is incompatible with `client`.
     *
     * @param data.format The format of the message. must be used with `schema`.  This parameter is incompatible with `client`.
     *
     * @returns Report OK
     * @throws ApiError
     */
    public static postValidate(
        data: PostValidateData,
    ): CancelablePromise<PostValidateResponse> {
        return __request(OpenAPI, {
            method: "POST",
            url: "/validate",
            headers: {
                client: data.client,
            },
            query: {
                schema: data.schema,
                format: data.format,
            },
            body: data.requestBody,
            mediaType: "text/csv",
            errors: {
                400: "Bad Request",
            },
        });
    }
}
