#!/usr/bin/env bash

# Pretty colors for echo -e
RED="\e[1;91m"
GREEN="\e[1;92m"
YELLOW="\e[1;33m"
NORMAL="\e[0m"
WHITE="\e[1;97m"

# HERE = the leaf directory we are running from (without any slashes)
HERE=${PWD##*/}

# the command you're running (plan by default)
TFCMD=${TFCMD:-plan}
VERBOSE=${VERBOSE:-0}

# Where is this script located (and thus, where are the configuration files)?
SCRIPT_DIR="$(dirname "$(realpath "${0}")")"
CONFIGS_DIR="${SCRIPT_DIR?}/configurations"

# Prints the usage
function usage() {
    echo "Usage: ${0} [--cmd <COMMAND>] [--env <ENVIRONMENT>] [--verbose]"
    echo ""
    echo -e "This script wraps around terraform to deploy your environment with the right configuration"
    echo ""
    echo -e "\t--cmd | -c <COMMAND>      Sets the terraform command and may alternatively be specified through \${TFCMD} (default: \"plan\")"
    echo -e "\t--env | -e <ENVIRONMENT>  Sets the environment and may alternatively be specified through \${ENVIRONMENT} (default: \"dev\")"
    echo -e "\t--verbose                 Produces verbose output"
}

# Returns 0 if the path is readable, and 1 otherwise
function stat_file() {
    RESULT=0
    if [[ ! -r "${1?}" ]]; then
        echo -e "${RED?}ERROR: \"${1?}\" is not readable.${NORMAL?}"
        RESULT=1
    else
        if [[ ${VERBOSE?} != 0 ]]; then
            echo -e "${GREEN?}OK:${NORMAL?} \"${1?}\" exists and is readable."
        fi
    fi

    return ${RESULT?}
}

#
# Parse the arguments
#
while [[ ! -z "${1}" ]]; do
    case "${1}" in
    "--cmd" | "-c")
        if [[ ! -z "${2}" ]]; then
            TFCMD="${2}"
        else
            echo -e "${RED?}ERROR:${NORMAL?} --cmd does not have a value."
            usage
            exit 1
        fi
        shift
        ;;
    "--env" | "-e")
        if [[ ! -z "${2}" ]]; then
            ENVIRONMENT="${2}"
        else
            echo -e "${RED?}ERROR:${NORMAL?} --env does not have a value."
            usage
            exit 1
        fi
        shift
        ;;
    "--help" | "-h")
        usage
        exit 0
        ;;
    "--verbose")
        VERBOSE=1
        ;;
    "--")
        shift
        break
        ;;
    *)
        echo -e "${YELLOW?}WARNING:${NORMAL?} Ignoring unrecognized option: \"${1}\""
        ;;
    esac

    shift
done

#
# Do real work
#

# Set default Azure subscription (and allow override)
az account set -s ${AZ_SUBSCRIPTION_ID:-7d1e3999-6577-4cd5-b296-f518e5c8e677}

# If not set, we assume you're targetting 'dev'
ENVIRONMENT="${ENVIRONMENT:-dev}"

# Set up the results masks
EXPECTED_RESULTS=""
ACTUAL_RESULTS=""

# Validate configuration directory
EXPECTED_RESULTS="${EXPECTED_RESULTS?}0"
stat_file "${CONFIGS_DIR?}/" # NOTE: trailing / to make this a dir
ACTUAL_RESULTS="${ACTUAL_RESULTS?}${?}"

# Validate tfvars file existence
TFVARS="${CONFIGS_DIR?}/${ENVIRONMENT?}.tfvars"
EXPECTED_RESULTS="${EXPECTED_RESULTS?}0"
stat_file "${TFVARS?}"
ACTUAL_RESULTS="${ACTUAL_RESULTS?}${?}"

# Validate backend config
BACKEND_CONFIG="${CONFIGS_DIR?}/${ENVIRONMENT?}.tfbackend"
EXPECTED_RESULTS="${EXPECTED_RESULTS?}0"
stat_file "${BACKEND_CONFIG?}"
ACTUAL_RESULTS="${ACTUAL_RESULTS?}${?}"

if [[ "${ACTUAL_RESULTS?}" != "${EXPECTED_RESULTS?}" ]]; then
    echo -e "${RED?}There were errors... aborting!${NORMAL?}"
    echo -e "\tResults Mask: ${ACTUAL_RESULTS?}/${EXPECTED_RESULTS?}"
    exit 1
fi

if [[ ${VERBOSE?} != 0 ]]; then
    echo -e "${GREEN?}OK:${NORMAL?} Checks passed, proceeding..."
fi

# TODO: manipulate 'HERE' to not include the nn- prefix (if it includes it at all but not if it doesn't)
_DASH_INDEX=$(expr index "${HERE?}" '-')
HERE=${HERE?:${_DASH_INDEX?}}

# Initialize with our backend
EXPECTED_RESULTS="${EXPECTED_RESULTS?}0"
terraform init \
    --reconfigure \
    --backend-config=<(cat ${BACKEND_CONFIG?} | sed "s/__STAGE__/${HERE?}/g")
ACTUAL_RESULTS="${ACTUAL_RESULTS?}${?}"

# Now do whatever you asked terraform to do (but only if we did not encounter any 'significant' errors)
if [[ "${ACTUAL_RESULTS?}" == "${EXPECTED_RESULTS?}" ]]; then
    echo "--------------------------------------------------------------------------------"
    if [[ "${VERBOSE?}" != "0" ]]; then
        echo -e "${WHITE?}Executing terraform ${TFCMD?}${NORMAL?}..."
    fi
    case "${TFCMD?}" in
    graph|output|state*)
        # Graph & output are special in that they do not like arguments
        EXPECTED_RESULTS="${EXPECTED_RESULTS?}0"
        terraform ${TFCMD}
        ACTUAL_RESULTS="${ACTUAL_RESULTS?}${?}"
        ;;

    import*)
        # Some commands require arguments in a different location
        EXPECTED_RESULTS="${EXPECTED_RESULTS?}0"
        TFCMD_BEFORE=$(echo "${TFCMD?}" | cut -d' ' -f 1)
        TFCMD_AFTER=$(echo "${TFCMD?}" | sed 's/[^ ]* //')
        terraform ${TFCMD_BEFORE?} \
            --var-file "${TFVARS?}" \
            ${TFCMD_AFTER?}
        ACTUAL_RESULTS="${ACTUAL_RESULTS?}${?}"
        ;;

    *)
        EXPECTED_RESULTS="${EXPECTED_RESULTS?}0"
        terraform ${TFCMD?} \
            --var-file "${TFVARS?}"
        ACTUAL_RESULTS="${ACTUAL_RESULTS?}${?}"
        ;;
    esac
fi

# Report results
echo "--------------------------------------------------------------------------------"
RC=1

if [[ "${ACTUAL_RESULTS?}" != "${EXPECTED_RESULTS?}" ]]; then
    echo -e "${RED?}We encountered errors...${NORMAL?}"
    echo -e "\tResults Mask: ${ACTUAL_RESULTS?}/${EXPECTED_RESULTS?}"
else
    if [[ ${VERBOSE?} != 0 ]]; then
        echo -e "${GREEN?}OK:${NORMAL?} everything went well..."
    fi

    RC=0
fi

exit ${RC?}
