name: Find next person on call
on:
  workflow_dispatch:
  push: 
    branches:
      - feature/12568-AddPDRotationSlack
  # schedule:
  #   - cron: "0 5 * * MON" #UTC-5
  #   - cron: '0 11 * * 1-5'
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Changes
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0

    - name: Get PD oncall schedule
      id: PD
      shell: pwsh
      run: |
        ./.github/scripts/PagerDutyAlerts/TriggerPDApi.ps1 -PD_KEY "${{ secrets.PD_ROTATION_SLACK_NOTIFICATION }}"    
    
    - name: Get PD onCall Details
      id: PDOnCall
      shell: pwsh
      run: |
        echo  ${env:OnCallPerson}

    - name: Slack Notification
      uses: ./.github/actions/notifications
      with:
        method: slack
        title: Pagerduty 
        message: |
          ${{ steps.PDOnCall.outputs.LIST }}
        icon-emoji: ':bell:'
        channel: pagerduty-alert-dump
        webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        color: warning