name: GHA to Check terraform-automation Secret Expiration

on:
  push:
    branches:
        - feature/set-slack-notification-tf-auto-secret-expiry

jobs:
  check-certificates:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Connect to VPN & Login into Azure
        uses: ./.github/actions/vpn-azure
        with:
          tls-key: ${{ secrets.TLS_KEY }}
          ca-cert: ${{ secrets.CA_CRT}}
          user-crt: ${{ secrets.USER_CRT }}
          user-key: ${{ secrets.USER_KEY }}
          sp-creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - name: Get the app secret details
        id: secret_check
        run: |
          secret_info=$(az ad app show --id ${{ secrets.TF_APP_REGIS_ID }} --query "passwordCredentials[0]" --output json)
          expiry_date=$(echo $secret_info | jq -r '.endDateTime')
          days_until_expiry=$(( ( $(date -d "$expiry_date" +%s) - $(date -u +%s) + 43200 ) / 86400 ))
      
      - name: Slack Notification
        if: ${{ steps.secret_check.outputs.days_until_expiry <= 30 }}
        uses: ./.github/actions/notifications
        with:
          method: slack
          title: App-registration Expiry
          message: |
             "Terraform-automation app-registration secret will expire in $days_until_expiry"
          icon-emoji: ':bell:'
          channel: pagerduty-alert-dump
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          color: warning
          
      