name: Auto Create Pull Request 
on:
  push:
    branches:
      - feature/autocreate-pr-tfplan-output
jobs:
  Auto_Create_PR:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: operations/app/terraform/vars/prod
    steps:
      - name: Check Out Repo Changes
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Connect to VPN and login to Azure
        uses: ./.github/actions/vpn-azure
        with:
          env-name: ${{ needs.pre_job.outputs.env_name }}
          tls-key: ${{ secrets.TLS_KEY }}
          ca-cert: ${{ secrets.CA_CRT}}
          user-crt: ${{ secrets.USER_CRT }}
          user-key: ${{ secrets.USER_KEY }}
          sp-creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}
          tf-auth: true
      - name: Set up Terraform V1.2.0
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: 1.2.0
          terraform_wrapper: false
      
      - name: Terraform init
        id: init
        run: terraform init -input=false
 
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
    
      - name: Terraform validate
        id: validate
        run: terraform validate
        continue-on-error: true
 
      # - name: Terraform Show
      #   id: show
      #   run: |
      #     run: terraform show -no-color ${{ steps.plan.outputs.tfplan }} 2>&1 > /tmp/plan.txt
      #   continue-on-error: true

      # - name: Format terraform
      #   id: format
      #   run: |
      #     $output=Get-Content "/tmp/plan.txt" -Raw
      #     Write-Host $output
      #     echo "tfplan=$output" 
      #   shell: pwsh
      #   continue-on-error: true
        
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          args: '-var="is_temp_env=true" -target=module.azure_dashboard -out tf.plan'
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -target=module.azure_dashboard -no-color -out=tfplan
        continue-on-error: true
          
      - name: Terraform Show
        id: show
        run: terraform show -no-color ${{ steps.plan.outputs.tfplan }} 2>&1 > /tmp/plan.txt
        continue-on-error: true

      - name: Read tfplan
        id: terraformplan
        uses: juliangruber/read-file-action@v1
        with:
          path: /tmp/plan.txt
    
      - name: Echo terraformplan
        run: echo "${{ steps.terraformplan.outputs.content }}"
        continue-on-error: true

      - name: "Prepare a Pull Request from ${{ env.BRANCH_NAME }} into production branch"
        uses: k3rnels-actions/pr-update@f22e3c8a08dc39f6d41b4cb44ad8250c40c19261
        id: pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Deployment of terraform"
          pr_source: feature/autocreate-pr-tfplan-ouput
          pr_target: "feature/autocreate-pr-with-tfplan-output"
          pr_labels: DevOps,reportstream
          pr_assignees: supriyaaddagada
          pr_body: ${{ steps.terraformplan.outputs.content }}

      - name: "Produce Pull Request URL"
        run: |
          echo "PR URL: https://github.com/CDCgov/prime-reportstream/pull/${{ steps.pr.outputs.pr_nr }}"
          echo "PR Id:  ${{ steps.pr.outputs.pr_nr }}"

      # - run: node ./.github/actions/pr-comment/comment.js
      #   env:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     issue_number: ${{ steps.pr.outputs.pr_nr }}
      #     repo: 'prime-reportstream'
      #     owner: supriyaaddagada
      #     website_link: ${{ steps.terraform.outputs.tf_actions_output }}

     




      # - name: Post Plan
      #   uses: robburger/terraform-pr-commenter@v1
      #   with:
      #     commenter_type: plan
      #     commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
      #     commenter_exitcode: ${{ steps.plan.outputs.exitcode }}


      # - name: Terraform Plan
      #   id: plan
      #   run: |
      #     terraform plan -out=tfplan
      #     cat tfplan
      #     terraform plan > tfplan.txt
      #     cat tfplan.txt

      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: Latest terraform changes to prod
      #     signoff: false
      #     base: master
      #     branch: feature/myfeaturebranchname
      #     delete-branch: false
      #     title: 'AutoPR With Terraform Plan Change to Prod'
      #     body: |
      #       ## Terraform Plan outputs
      #       ````
      #       $(cat tfplan.txt)
      #       ````
      #     labels: |
      #       production
      #       DevOps
      #     assignees: |
      #       johnsmith
      #     reviewers: |
      #       johnsmith
      #       michaelkosh 
      #     draft: false
      
      # - name: Add Terraform Plan Output as Comment
      #   uses: mshick/add-pr-comment@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     message: |
      #       Terraform plan output:
      #       ```
      #       ${{ steps.plan.outputs.stdout }}
      #       ```

      # - name: Create Pull Request
      #   uses: gr2m/create-or-update-pull-request-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     title: "AutoPR With Terraform Plan Change to Prod"
      #     body: $(cat tfplan.txt) # "My pull request body"
      #     branch: "feature/autocreate-pr-with-tfplan-output-prod"
      #     commit-message: "Automatically created pull request with tf plan"
      #     author: "Lucas Dze"
      #     labels: DevOps, prime-reportstream
      #     #assignees: user1, user2
      #     reviewers: lucasdze, JosiahSiegel
      #     #team_reviewers: team1, team2
      #     auto-merge: squash
      #     update-pull-request-title-and-body: false

              # - name: Create Pull Request
      #   uses: thomaseizinger/create-pull-request@e3972219c86a56550fb70708d96800d8e24ba862
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     head: feature/autocreate-pr-with-tfplan-output-prod 
      #     base: master
      #     title: "AutoPR With Terraform Plan Change to Prod"
      #     body: |
      #       ## Terraform Plan outputs
      #       ````
      #       $(cat tfplan.txt)
      #       ````
      #     reviewers: |
      #       lucasdze
      #       JosiahSiegel
      #       jeremy-page

      # - name: Create Pull Request
      # #   uses: peter-evans/create-pull-request@6217f0d61d3e1fd1236b1cee861f010f84673f23
      #   with:
      #     #commit-message: Automatically created pull request with tf plan
      #     title: AutoPR With Terraform Plan Change to Prod
      #     base: master
      #     branch: feature/autocreate-pr-with-tfplan-output-prod 
      #     body: |
      #       $(cat tfplan.txt)
          # reviewers: |
          #   lucasdze
          #   JosiahSiegel
          #   jeremy-page
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     delete-branch: false
      #     draft: false

          