name: Database maintenance

on:
  push:
    branches:
      - josiahsiegel/add/db-maint

jobs:
  db_maint:
    name: "DB Maintenance - pdh${{ matrix.env }}-pgsql"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging] #[prod, staging]
        db: [prime_data_hub]
    #environment: ${{ matrix.env }}
    steps:
      - name: Check out changes
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - name: Get public ip
        shell: bash
        run: echo "PUBLIC_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)" >> $GITHUB_ENV

        # Allow runner db access
      - name: Add db access
        id: add-db-access
        uses: ./.github/actions/retry
        with:
          timeout_minutes: 120
          max_attempts: 6
          retry_wait_seconds: 30
          command: |
            az postgres server update -g prime-data-hub-${{ matrix.env }} -n pdh${{ matrix.env }}-pgsql --public-network-access "Enabled"
            sleep 30;
            az postgres server firewall-rule create -g prime-data-hub-${{ matrix.env }} -s pdh${{ matrix.env }}-pgsql -n github_actions_runner \
              --start-ip-address ${{ env.PUBLIC_IP }} --end-ip-address ${{ env.PUBLIC_IP }}
            az postgres server firewall-rule show -g prime-data-hub-${{ matrix.env }} -s pdh${{ matrix.env }}-pgsql -n github_actions_runner
          shell: bash

      - name: Run maint query
        uses: ./.github/actions/db-query
        with:
          pass: ${{ secrets[format('POSTGRESQL_{0}_PWD', matrix.env)] }}
          host: pdh${{ matrix.env }}-pgsql
          port: 5432
          user: prime
          database: ${{ matrix.db }}
          query: |
            DO $$
            DECLARE
              need_vacuum boolean;
            BEGIN
              SELECT pg_stat_get_dead_tuples(oid) > 1000000 INTO need_vacuum
              FROM pg_class
              WHERE relname = 'item_lineage';

              IF need_vacuum THEN
                RAISE NOTICE 'Running VACUUM on item_lineage';
                VACUUM VERBOSE public.item_lineage;
              ELSE
                RAISE NOTICE 'VACUUM not needed for item_lineage';
              END IF;

              SELECT pg_stat_get_dead_tuples(oid) > 1000000 INTO need_vacuum
              FROM pg_class
              WHERE relname = 'action_log';

              IF need_vacuum THEN
                RAISE NOTICE 'Running VACUUM on action_log';
                VACUUM VERBOSE public.action_log;
              ELSE
                RAISE NOTICE 'VACUUM not needed for action_log';
              END IF;

              ANALYZE VERBOSE;
            END $$;

        # Remove runner db access
      - name: Remove db access
        if: always()
        continue-on-error: true
        shell: bash
        run: |
          az postgres server firewall-rule delete -g prime-data-hub-${{ matrix.env }} -s pdh${{ matrix.env }}-pgsql -n github_actions_runner --yes;
          sleep 10;
          az postgres server update -g prime-data-hub-${{ matrix.env }} -n pdh${{ matrix.env }}-pgsql --public-network-access "Disabled";
          sleep 30;
