name: Database maintenance

on:
  push:
    branches:
      - josiahsiegel/add/db-maint

env:
  VACUUM_CMD: "VACUUM ANALYZE"

jobs:
  db_maint:
    name: "DB Maintenance - pdh${{ matrix.env }}-pgsql"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging] #[prod, staging]
        db: [prime_data_hub]
    #environment: ${{ matrix.env }}
    steps:
      - name: Check out changes
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - name: Get public ip
        shell: bash
        run: echo "PUBLIC_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)" >> $GITHUB_ENV

        # Allow runner db access
      - name: Add db access
        id: add-db-access
        uses: ./.github/actions/retry
        with:
          timeout_minutes: 120
          max_attempts: 6
          retry_wait_seconds: 30
          command: |
            az postgres server update -g prime-data-hub-${{ matrix.env }} \
              -n pdh${{ matrix.env }}-pgsql --public-network-access "Enabled"
            sleep 30;
            az postgres server firewall-rule create -g prime-data-hub-${{ matrix.env }} \
              -s pdh${{ matrix.env }}-pgsql -n github_actions_runner \
              --start-ip-address ${{ env.PUBLIC_IP }} --end-ip-address ${{ env.PUBLIC_IP }}
            az postgres server firewall-rule show -g prime-data-hub-${{ matrix.env }} \
              -s pdh${{ matrix.env }}-pgsql -n github_actions_runner
          shell: bash

      - name: Run maint query
        id: query
        uses: yakubique/query-postgresql@v1.2
        with:
          query: './.github/scripts/database_maintenance/identify_bloat.sql'
          host: pdh${{ matrix.env }}-pgsql.postgres.database.azure.com
          port: 5432
          username: prime@pdh${{ matrix.env }}-pgsql.postgres.database.azure.com
          password: ${{ secrets[format('POSTGRESQL_{0}_PWD', matrix.env)] }}
          db: ${{ matrix.db }}
          ssl: 'true'
          from_file: true
          to_file: true

      - name: Read JSON output
        id: read_json
        run: |
          content=$(cat "${{ steps.query.outputs.result }}")
          echo "tables=$(echo "$content" | jq -c '.')" >> $GITHUB_OUTPUT
  
      - name: Run vacuum for each table
        env:
          TABLES: ${{ steps.read_json.outputs.tables }}
          PGPASSWORD: ${{ secrets[format('POSTGRESQL_{0}_PWD', matrix.env)] }}
          VACUUM_CMD: ${{ env.VACUUM_CMD }}
        run: |
          tables=$(echo "$TABLES" | jq -c '.[]')
          for table in $tables; do
            schema_name=$(echo "$table" | jq -r '.schemaname')
            table_name=$(echo "$table" | jq -r '.tblname')
            
            echo "Running vacuum for table: $schema_name.$table_name"
            psql -h pdh${{ matrix.env }}-pgsql.postgres.database.azure.com -p 5432 \
              -U prime@pdh${{ matrix.env }}-pgsql.postgres.database.azure.com \
              -d ${{ matrix.db }} -c "$VACUUM_CMD $schema_name.$table_name;"
          done
  
        # Remove runner db access
      - name: Remove db access
        if: always()
        continue-on-error: true
        shell: bash
        run: |
          az postgres server firewall-rule delete -g prime-data-hub-${{ matrix.env }} \
            -s pdh${{ matrix.env }}-pgsql -n github_actions_runner --yes;
          sleep 10;
          az postgres server update -g prime-data-hub-${{ matrix.env }} \
            -n pdh${{ matrix.env }}-pgsql --public-network-access "Disabled";
          sleep 30;
