name: "Auto-run Smoke test in Staging"

on:
  push:
    branches:
      - "feature/automate-predeployment-smoketest"

env:
  DB_USER: ${{ secrets.POSTGRESQL_STG_ADMIN_USER }}
  DB_PASSWORD: ${{ secrets.POSTGRESQL_STAGING_PWD }}

jobs:
  pre_job:
    name: Pre Job
    runs-on: ubuntu-latest
    outputs:
      has_router_change: ${{ steps.build_vars.outputs.has_router_change }}
    steps:
      - name: "Check out changes"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Build vars
        id: build_vars
        uses: ./.github/actions/build-vars

  smoketest_prime_router:
    needs: pre_job
    name: Run SmokeTest in Prime Router
    runs-on: ubuntu-latest

    steps:
      - name: "Check out changes"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Get runner ip
        id: runner_ip
        uses: ./.github/actions/runner-ip

      - name: Connect to VPN & Login into Azure 
        uses: ./.github/actions/vpn-azure
        with:
          tls-key: ${{ secrets.TLS_KEY }}
          ca-cert: ${{ secrets.CA_CRT}}
          user-crt: ${{ secrets.USER_CRT }}
          user-key: ${{ secrets.USER_KEY }}
          sp-creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - name: Add Runner IP to Postgres Firewall
        run: |
          az postgres server firewall-rule create --resource-group prime-data-hub-staging --server-name ${{ secrets.POSTGRESQL_STG_SERVER_NAME }} --name GHA --start-ip-address ${{ steps.runner_ip.outputs.ip-address }} --end-ip-address ${{ steps.runner_ip.outputs.ip-address }}

      - name: Set up JDK 11
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b

      - name: Spin up build containers
        run: docker-compose -f docker-compose.postgres.yml up -d

      - name: Build Prime Router Package
        run: ./gradlew package -Pshowtests
      
      - name: Spin up vault
        working-directory: prime-router
        timeout-minutes: 1
        run: |
          mkdir .vault/env
          touch .vault/env/.env.local
          docker-compose -f docker-compose.yml up -d vault
          while [ ! -s .vault/env/.env.local ]; do sleep 1; done
          echo "loaded env vars"

      - name: Spin up containers
        working-directory: prime-router
        shell: bash
        run: docker-compose -f docker-compose.yml up -d prime_dev sftp azurite


      - name: Give some time for the container to start
        run: |
          echo "sleeping 30"
          sleep 30
          echo "wake up"

      - name: set staging env for database
        run: |
          export POSTGRES_PASSWORD=${{ secrets.POSTGRESQL_STAGING_PWD }};export POSTGRES_URL=jdbc:postgresql://pdhstaging-pgsql.postgres.database.azure.com:5432/prime_data_hub?sslmode=require;export POSTGRES_USER=${{ secrets.POSTGRESQL_STG_ADMIN_USER }}
      
      - name: Load the configuration
        working-directory: prime-router
        shell: bash
        run: |
         ./gradlew reloadTables
         ./gradlew reloadSettings

      - name: Correct sftp perms
        run: docker-compose exec -T sftp chmod 777 /home/foo/upload

      - name: Smoke tests
        run: |
          export $(xargs < .vault/env/.env.local)
          ./prime create-credential --type=UserPass --persist=DEFAULT-SFTP --user foo --pass pass
          ./gradlew testSmoke
          
      
      - name: Run Smoke Test in Staging
        working-directory: prime-router
        shell: bash
        run: ./prime test --env staging --key ${{ secrets.STG_API_KEY }}

      - name: Remove Runner IP from Postgres Firewall
        run: |
            az postgres server firewall-rule delete --resource-group prime-data-hub-staging --server-name ${{ secrets.POSTGRESQL_STG_SERVER_NAME }} --name GHA --yes
      
      

# jobs:
#   prepare_branch:
#     name: "Run Smoke test on the deployment branch"
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Check out changes"
#         uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

#       - name: Get runner ip
#         id: runner_ip
#         uses: ./.github/actions/runner-ip

#       - name: Connect to VPN & Login into Azure 
#         uses: ./.github/actions/vpn-azure
#         with:
#           tls-key: ${{ secrets.TLS_KEY }}
#           ca-cert: ${{ secrets.CA_CRT}}
#           user-crt: ${{ secrets.USER_CRT }}
#           user-key: ${{ secrets.USER_KEY }}
#           sp-creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

#       - name: Add Runner IP to Postgres Firewall
#         run: |
#           az postgres server firewall-rule create --resource-group prime-data-hub-staging --server-name ${{ secrets.POSTGRESQL_STG_SERVER_NAME }} --name GHA --start-ip-address ${{ steps.runner_ip.outputs.ip-address }} --end-ip-address ${{ steps.runner_ip.outputs.ip-address }}

#       - name: set staging env for database
#         run: |
#           export POSTGRES_PASSWORD=${{ secrets.POSTGRESQL_STAGING_PWD }};export POSTGRES_URL=jdbc:postgresql://pdhstaging-pgsql.postgres.database.azure.com:5432/prime_data_hub?sslmode=require;export POSTGRES_USER=${{ secrets.POSTGRESQL_STG_ADMIN_USER }}
      
#       - name: Spin up containers
#         id: spin_containers
#         run: |
#           docker-compose -f docker-compose.yml up -d prime_dev sftp azurite
          
#       - name: Give some time for the container to start
#         run: |
#           echo "sleeping 30"
#           sleep 30
#           echo "wake up"
      
#       - name: Load the configuration
#         run: |
#          ./gradlew reloadTables
#          ./gradlew reloadSettings

#       # - name: Build Prime Router Package
#       #   working-directory: prime-router
#       #   shell: bash
#       #   run: ./gradlew package -x fatjar -Pshowtests


#       # - name: Set up Node.js
#       #   uses: actions/setup-node@v2
#       #   with:
#       #     node-version: '14'

#       # - name: Install dependencies
#       #   run: npm install puppeteer

#       # - name: Login to Okta
#       #   env:
#       #     OKTA_USERNAME: ${{ secrets.OKTA_USERNAME }}
#       #     OKTA_PASSWORD: ${{ secrets.OKTA_PASSWORD }}
#       #   run: |
#       #     echo "
#       #     const puppeteer = require('puppeteer');

#       #     async function login() {
#       #       const browser = await puppeteer.launch();
#       #       const page = await browser.newPage();
#       #       await page.goto('https://${{ secrets.OKTA_DOMAIN }}');

#       #       await page.waitForSelector('#okta-signin-username');
#       #       await page.type('#okta-signin-username', process.env.OKTA_USERNAME);
#       #       await page.type('#okta-signin-password', process.env.OKTA_PASSWORD);
#       #       await page.click('#okta-signin-submit');

#       #       await page.waitForNavigation();

#       #       // You can perform further actions after successful login
#       #       // For example, retrieve user information
#       #       const userFullName = await page.evaluate(() => {
#       #         const fullNameElement = document.querySelector('.app-user-name');
#       #         return fullNameElement ? fullNameElement.textContent.trim() : null;
#       #       });
#       #       console.log('Logged in as:', userFullName);

#       #       await browser.close();
#       #     }

#       #     login();
#       #     " > login.js

#       #     npx --no-install puppeteer login.js


#       - name: Set up JDK 11
#         uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
#         with:
#           java-version: '11'
#           distribution: 'adopt'
#           cache: 'gradle'

#       - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b

#       - name: Build with Gradle
#         working-directory: prime-router
#         shell: bash
#         run: ./gradlew clean build

#       - name: Run Smoke Test in Staging
#         working-directory: prime-router
#         shell: bash
#         run: ./prime test --env staging --key ${{ secrets.STG_API_KEY }}


#       - name: Remove Runner IP to Postgres Firewall
#         run: |
#             az postgres server firewall-rule delete --resource-group prime-data-hub-staging --server-name ${{ secrets.POSTGRESQL_STG_SERVER_NAME }} --name GHA --yes
      