name: "Auto-run Smoke test in Staging"

on:
  push:
    branches:
      - "feature/automate-predeployment-smoketest"
  # workflow_dispatch:
  # schedule:
  #   # At 23:00 on Monday and Wednesday (https://crontab.guru/#0_16_*_*_1,3)
  #   # GitHub actions run in UTC (and EDT is UTC-4)
  #   # If this schedule changes, check any reminders that might be in slack with `/remind list`
  #   - cron: "0 23 * * 1,3"

jobs:
  prepare_branch:
    name: "Run Smoke test on the deployment branch"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out changes"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Get runner ip
        id: runner_ip
        uses: ./.github/actions/runner-ip

      - name: Connect to VPN & Login into Azure 
        uses: ./.github/actions/vpn-azure
        with:
          tls-key: ${{ secrets.TLS_KEY }}
          ca-cert: ${{ secrets.CA_CRT}}
          user-crt: ${{ secrets.USER_CRT }}
          user-key: ${{ secrets.USER_KEY }}
          sp-creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}

      - name: Add Runner IP to Postgres Firewall
        run: |
          az postgres server firewall-rule create --resource-group prime-data-hub-staging --server-name ${{ secrets.POSTGRESQL_STG_SERVER_NAME }} --name GHA --start-ip-address ${{ steps.runner_ip.outputs.ip-address }} --end-ip-address ${{ steps.runner_ip.outputs.ip-address }}

      - name: set staging env for database
        run: |
          export POSTGRES_PASSWORD=${{ secrets.POSTGRESQL_STAGING_PWD }};export POSTGRES_URL=jdbc:postgresql://pdhstaging-pgsql.postgres.database.azure.com:5432/prime_data_hub?sslmode=require;export POSTGRES_USER=${{ secrets.POSTGRESQL_STG_ADMIN_USER }}
      
      - name: Spin up build containers
        working-directory: prime-router
        shell: bash
        run: docker-compose -f docker-compose.postgres.yml up -d

      - name: Build Prime Router Package
        working-directory: prime-router
        shell: bash
        run: ./gradlew package -x fatjar -Pshowtests


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g @okta/okta-sdk-nodejs
          npm install -g @okta/okta-auth-js

      # - name: Login to Okta
      #   env:
      #     OKTA_USERNAME: ${{ secrets.OKTA_USERNAME }}
      #     OKTA_PASSWORD: ${{ secrets.OKTA_PASSWORD }}
      #   run: |
      #     echo "const okta = require('@okta/okta-sdk-nodejs');
      #     const authClient = require('@okta/okta-auth-js');

      #     const oktaDomain = ${{ secrets.OKTA_DOMAIN }};
      #     const username = process.env.OKTA_USERNAME;
      #     const password = process.env.OKTA_PASSWORD;

      #     async function login() {
      #       try {
      #         const authClient = new authClient.AuthenticationClient({
      #           issuer: 'https://${oktaDomain}/oauth2/default',
      #           clientId: ${{ secrets.OKTA_CLIENT_ID }},
      #           redirectUri: 'http://localhost:8080',
      #           scopes: ['openid', 'email', 'profile'],
      #         });

      #         const transaction = await authClient.signIn({ username, password });
      #         const sessionToken = await transaction.sessionToken;

      #         const client = new okta.Client({
      #           orgUrl: `https://${oktaDomain}`,
      #           token: sessionToken,
      #         });

      #         // Use the Okta SDK client for further operations
      #         // For example, retrieve user information
      #         const userInfo = await authClient.getUserInfo(sessionToken);
      #         const userId = userInfo.sub;
      #         console.log('Logged in as user ID:', userId);
      #       } catch (error) {
      #         console.error('Login failed:', error);
      #         process.exit(1);
      #       }
      #     }

      #     login();" > login.js

      #     node login.js

      - name: Run Smoke Test in Staging
        run: ./prime test --env staging --key ${{ secrets.STG_API_KEY }}


      - name: Remove Runner IP to Postgres Firewall
        run: |
            az postgres server firewall-rule delete --resource-group prime-data-hub-staging --server-name ${{ secrets.POSTGRESQL_STG_SERVER_NAME }} --name GHA --yes
      