name: Alert Stale Items from GitHub

on:
  workflow_dispatch:
  push: 
    branches:
      - feature/stale-items-report
  
jobs:
  alert_stale_items:
    name: Alert on Stale items in github
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          fetch-depth: 0
      - name: Get Stale branches
        id: StaleBranches
        run: echo "Branches=$(./.github/scripts/stale_items_report/oldbranches.sh)" >> stale_branches.txt
        shell: bash

      - name: Get stale issues
        id: staleIssues
        shell: pwsh
        run: echo "Issues=$(./.github/scripts/stale_items_report/StaleIssues.ps1)" >> stale_issues.txt
      
      - name: Get stale pull requests
        id: StalePRs
        shell: pwsh
        run: |
          echo "Pull Requests=$(./.github/scripts/stale_items_report/StalePullRequests.ps1)" >> stale_prs.txt
      
      - uses: MeilCli/slack-upload-file@v3
        id: message
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'stale_prs.txt'
          initial_comment: 'post by slack-upload-file'
      - run: 'echo ${{ fromJson(steps.message.outputs.response).files[0].file.permalink }}'

      # - name: Upload to slack step
      #   uses: adrey/slack-file-upload-action@master
      #   with:
      #     token: ${{ secrets.SLACK_TOKEN }}
      #     path: stale_prs.txt
      #     channel: ${{ secrets.SLACK_CHANNEL }}
      #     title: 'Stale items report'

      # - name: Upload to slack step
      #    uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     data: |
      #       {
      #         "text": "Stale Items Report:",
      #         "attachments": ${{ toJSON(fromJSON(steps.StalePRs.outputs.stdout)) }}
      #       }