name: Alert Stale Items from GitHub

on:
  workflow_dispatch:
  push: 
    branches:
      - feature/stale-items-report
  
jobs:
  alert_stale_items:
    name: Alert on Stale items in github
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          fetch-depth: 0
      - name: Get Stale branches
        id: stalebranches
        run: echo "branches=$(./.github/scripts/stale_items_report/oldbranch.sh)" >> $GITHUB_OUTPUT
        shell: bash

      - name: print Stale branches
        id: printstalebranches
        run: echo "${{ steps.stalebranches.outputs.branches }}"
        shell: bash
      

      # - uses: MeilCli/slack-upload-file@v3
      #   id: message
      #   with:
      #     slack_token: ${{ secrets.SLACK_TOKEN }}
      #     channel_id: 'C04UBN6R9EF'
      #     file_path: 'stale_prs.json'
      #     initial_comment: 'Stale Items report'
      # - run: 'echo ${{ fromJson(steps.message.outputs.response).files[0].file.permalink }}'

      # - name: Stale Items report
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     payload-file-path: "stale_prs.json"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name: Upload JSON file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: data
      #     path: stale_prs.json

      # - name: Send Slack notification
      #   uses: rtCamp/action-slack-notify@v2
      #   with:
      #     status: ${{ job.status }}
      #     text: 'A new JSON file has been generated and attached.'
      #     title: 'JSON File Notification'
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
     