name: Alert Stale Items from GitHub

on:
  workflow_dispatch:
  push: 
    branches:
      - feature/stale-items-report
  
jobs:
  alert_stale_items:
    name: Alert on Stale items in github
    runs-on: windows-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          fetch-depth: 0
      # - name: Get Stale branches
      #   id: StaleBranches
      #   run: echo "Branches=$(./.github/scripts/stale_items_report/oldbranches.sh)" >> stale_branches.txt
      #   shell: bash

      # - name: Get stale issues
      #   id: staleIssues
      #   shell: powershell   
      #   run: echo "Issues=$(./.github/scripts/stale_items_report/StaleIssues.ps1)" >> stale_issues.txt
      
      - name: Get stale pull requests
        id: StalePRs
        shell: powershell   
        run: |  
          echo "::set-output name=stdout::$(./.github/scripts/stale_items_report/StalePullRequests.ps1)"
          
      - name: Get stale prs
        id: StalePRItems
        shell: powershell   
        run: echo "::set-output name=test::$(./.github/scripts/stale_items_report/StalePullRequests.ps1)"
        
      # - name: Get stale pull requests
      #   id: GetStalePRS
      #   run: |
      #      echo "PullRequests=$(./.github/scripts/stale_items_report/StalePullRequests.ps1)" >> $GITHUB_OUTPUT
      #      echo ::set-output name=StalePRs:: $PullRequests
      #      echo $StalePRs=$PullRequests
      #   env:
      #     PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }}
      #   shell: pwsh
      #   continue-on-error: true

      # - name: Stale PRs
      #   id: prs
      #   env: 
      #     PullRequests: $(./.github/scripts/stale_items_report/StalePullRequests.ps1) 
      #   run: |
      #      write-output $env:PullRequests
      #   shell: powershell     

      - name: Stale PRs
        id: pullrequests
        run: |
          echo  ${{ steps.StalePRs.outputs.stdout }} 
      

      # - uses: MeilCli/slack-upload-file@v3
      #   id: message
      #   with:
      #     slack_token: ${{ secrets.SLACK_TOKEN }}
      #     channel_id: 'C04UBN6R9EF'
      #     file_path: 'stale_prs.json'
      #     initial_comment: 'Stale Items report'
      # - run: 'echo ${{ fromJson(steps.message.outputs.response).files[0].file.permalink }}'

      # - name: Stale Items report
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     payload-file-path: "stale_prs.json"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name: Upload JSON file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: data
      #     path: stale_prs.json

      # - name: Send Slack notification
      #   uses: rtCamp/action-slack-notify@v2
      #   with:
      #     status: ${{ job.status }}
      #     text: 'A new JSON file has been generated and attached.'
      #     title: 'JSON File Notification'
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
     